# Generated by Django 4.0.3 on 2022-06-15 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('lane', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=40)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
