# Generated by Django 4.0.3 on 2022-06-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='type',
            field=models.CharField(default='doctor', max_length=40),
            preserve_default=False,
        ),
    ]
